[package]
name = "typst-plantuml"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.57", features = ["derive"] }
log = "0.4.29"
notify = "8.2.0"
pretty_env_logger = "0.5.0"
rootcause = "0.11.1"
typst-syntax = "0.14.2"
